CREATE TABLE `biodata_mhs` (
  `no_mhs` int(255) NOT NULL AUTO_INCREMENT,
  `nim_mhs` varchar(20) DEFAULT NULL,
  `kode` varchar(100) DEFAULT NULL,
  `alamat` varchar(200) DEFAULT NULL,
  `kota` varchar(50) DEFAULT NULL,
  `no_ijasah` varchar(50) DEFAULT NULL,
  `asal_sekolah` varchar(100) DEFAULT NULL,
  `jurusan_sma` varchar(50) DEFAULT NULL,
  `kota_lahir` varchar(50) DEFAULT NULL,
  `tanggal_lahir` varchar(50) DEFAULT NULL,
  `tahun_lulus` varchar(10) DEFAULT NULL,
  `pt_awal` varchar(200) DEFAULT NULL,
  `alamat_pt` varchar(200) DEFAULT NULL,
  `fakultas_pt` varchar(200) DEFAULT NULL,
  `jurusan_pt` varchar(200) DEFAULT NULL,
  `sks_pt` varchar(10) DEFAULT NULL,
  `telepon_mhs` varchar(20) DEFAULT NULL,
  `kode_pos` varchar(10) DEFAULT NULL,
  `sex` varchar(20) DEFAULT NULL,
  `oleh` varchar(50) DEFAULT NULL,
  `tgl_update` varchar(50) DEFAULT NULL,
  `stt` varchar(5) DEFAULT NULL,
  `nim_asal` varchar(20) DEFAULT NULL,
  `tgl_input` date DEFAULT NULL,
  `jam_input` time DEFAULT NULL,
  `tgl_ijazah` varchar(50) DEFAULT NULL,
  `desa` varchar(50) DEFAULT NULL,
  `kecamatan` varchar(50) DEFAULT NULL,
  `provinsi` varchar(50) DEFAULT NULL,
  `catatan_pmb` varchar(255) DEFAULT NULL,
  `email_mhs` varchar(50) DEFAULT NULL,
  `nik_mhs` varchar(50) DEFAULT NULL,
  `agama` varchar(30) DEFAULT NULL,
  `do` int(10) NOT NULL DEFAULT '0',
  `kewarganegaraan` varchar(50) DEFAULT NULL,
  `passport` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`no_mhs`),
  KEY `no_mhs` (`no_mhs`),
  KEY `nim` (`kode`)
) ENGINE=MyISAM AUTO_INCREMENT=33431 DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;
