CREATE TABLE `kuliah_skripsi` (
  `id` int(50) NOT NULL AUTO_INCREMENT,
  `tgl` datetime DEFAULT NULL,
  `nim` varchar(20) DEFAULT NULL,
  `id_thn` int(10) DEFAULT NULL,
  `kode_fp` varchar(10) DEFAULT NULL,
  `semester` int(5) DEFAULT NULL,
  `tahun_akademik` varchar(20) DEFAULT NULL,
  `stt_skripsi` varchar(20) DEFAULT NULL,
  `tgl_daftar` varchar(50) DEFAULT NULL,
  `judul_skripsi` text,
  `judul_acc` text,
  `tgl_ujian` varchar(30) DEFAULT NULL,
  `nilai` varchar(10) DEFAULT NULL,
  `keterangan` varchar(200) DEFAULT NULL,
  `stt` int(5) DEFAULT NULL,
  `key` varchar(100) NOT NULL,
  `stts_mhs` int(10) DEFAULT '1' COMMENT '1= belum lulus, 2= lulus',
  `kota` varchar(100) DEFAULT NULL,
  `kode_mk1` varchar(100) DEFAULT NULL,
  `stt_cek` int(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`),
  UNIQUE KEY `key` (`key`)
) ENGINE=MyISAM AUTO_INCREMENT=9914 DEFAULT CHARSET=latin1;
