CREATE TABLE `kuliah_aktif_now` (
  `id_kuliah` int(100) NOT NULL AUTO_INCREMENT,
  `tgl_simpan` date DEFAULT NULL,
  `id_thn_kuliah` int(100) DEFAULT NULL,
  `tahun` varchar(10) DEFAULT NULL,
  `smtr` varchar(10) DEFAULT NULL,
  `kode_fp` varchar(10) DEFAULT NULL,
  `angkatan` varchar(20) DEFAULT NULL,
  `kode_mk` varchar(20) DEFAULT NULL,
  `id_ruang` int(10) DEFAULT NULL,
  `kelas` varchar(100) DEFAULT NULL,
  `jenis_kelas` varchar(10) DEFAULT '0' COMMENT '1=Reguler 2=Khusus',
  `id_dosen` int(10) DEFAULT NULL,
  `jam_kuliah` varchar(50) DEFAULT NULL,
  `hari` varchar(30) DEFAULT NULL,
  `tgl_mulai` date NOT NULL DEFAULT '2025-01-01',
  `tgl_akhir` date NOT NULL DEFAULT '2025-01-01',
  `stts` varchar(10) DEFAULT '1' COMMENT '1 bisa diedit 2 dikunci',
  `kode_grop` varchar(50) DEFAULT NULL,
  `j_mhs` int(10) DEFAULT '0',
  `sks` int(10) DEFAULT '0',
  `sttg` int(10) DEFAULT NULL,
  `stt_nilai` varchar(10) DEFAULT '0' COMMENT '0 = belum diinput, 1= Diinput belum lengkap, 2 = terkirim ke baea',
  `kelas_kuliah` varchar(100) NOT NULL DEFAULT '0',
  `kode_mk1` varchar(20) DEFAULT NULL,
  `stt_nilai_open` int(5) DEFAULT '1',
  `stt_sett` int(5) DEFAULT '1' COMMENT '1 iya 0 tidak',
  `view_mhs` int(5) NOT NULL DEFAULT '0' COMMENT '0 = hidden 1 = ketok',
  `nama_mk` varchar(50) DEFAULT NULL,
  `nama_dsn` varchar(100) DEFAULT NULL,
  `tgl_add_nilai` datetime DEFAULT NULL,
  `rps` varchar(200) DEFAULT NULL,
  `stt_rps` int(100) NOT NULL DEFAULT '0',
  `nama_kelas` varchar(50) DEFAULT NULL,
  `smtr_masuk` int(10) DEFAULT '1',
  `kode_sinc` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id_kuliah`),
  UNIQUE KEY `id` (`id_kuliah`),
  KEY `id_dosen` (`id_dosen`),
  KEY `kode_mk` (`kode_mk`)
) ENGINE=MyISAM AUTO_INCREMENT=64013 DEFAULT CHARSET=latin1;