CREATE TABLE `kuliah_jurnal` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `updt` datetime DEFAULT NULL,
  `kuliah_kelas` varchar(50) DEFAULT NULL,
  `id_thn` int(10) DEFAULT NULL,
  `id_kuliah_aktif` int(20) DEFAULT NULL,
  `tahun` int(10) DEFAULT NULL,
  `semester` varchar(10) DEFAULT NULL,
  `kode_fp` varchar(10) DEFAULT NULL,
  `dosen` int(10) DEFAULT NULL,
  `kode_mk` varchar(20) DEFAULT NULL,
  `sesi` int(10) DEFAULT NULL,
  `jurnal` text,
  `tanggal` varchar(50) DEFAULT NULL,
  `stts` varchar(10) DEFAULT '0',
  `stts_prodi` varchar(10) DEFAULT '0',
  `stts_absen` int(10) DEFAULT '0',
  `absen_mhs` int(10) NOT NULL DEFAULT '0' COMMENT '0 off 1 buka',
  `mulai` datetime NOT NULL,
  `selesai` datetime NOT NULL,
  `start` int(100) NOT NULL DEFAULT '0',
  `end` int(100) NOT NULL DEFAULT '0',
  `tgl_absen_mhs` datetime DEFAULT NULL,
  `mhs1` varchar(100) DEFAULT NULL,
  `mhs2` varchar(100) DEFAULT NULL,
  `token` varchar(50) DEFAULT NULL,
  `token_expire` datetime NOT NULL,
  `metode` varchar(100) DEFAULT NULL,
  `tugas` varchar(200) DEFAULT NULL,
  `subCPMK` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `dosen` (`dosen`) USING BTREE,
  KEY `kode_mk` (`kode_mk`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=190099 DEFAULT CHARSET=latin1;

