CREATE TABLE `mahasiswa` (
  `no_mhs` int(255) NOT NULL AUTO_INCREMENT,
  `nim` varchar(30) NOT NULL,
  `password` varchar(20) DEFAULT NULL,
  `passwd` varchar(50) DEFAULT NULL,
  `nama_mhs` varchar(100) DEFAULT NULL,
  `alamat` varchar(200) DEFAULT NULL,
  `kota` varchar(30) DEFAULT NULL,
  `no_ijasah` varchar(30) DEFAULT NULL,
  `asal_sekolah` varchar(100) DEFAULT NULL,
  `jurusan_sma` varchar(50) DEFAULT NULL,
  `kota_lahir` varchar(30) DEFAULT NULL,
  `tgl_lahir` varchar(100) DEFAULT NULL,
  `tanggal_lahir` varchar(50) DEFAULT NULL,
  `tahun_lulus` varchar(5) DEFAULT NULL,
  `kode_fakultas` varchar(5) DEFAULT NULL,
  `kode_jurusan` varchar(5) DEFAULT NULL,
  `semester` int(5) DEFAULT NULL,
  `status` varchar(10) DEFAULT NULL COMMENT '1 = belum daftar ulang\r\n2 = daftar ulang\r\n3 = sudah program\r\n22 = modif\r\n23 = bypass program\r\n4 = Cuti\r\n5=meninggal\r\n10 = lulus',
  `angkatan` varchar(10) DEFAULT NULL,
  `jenis` varchar(50) DEFAULT NULL,
  `gelombang` varchar(5) DEFAULT NULL,
  `bakat_minat` varchar(200) DEFAULT NULL,
  `pt_awal` varchar(200) DEFAULT NULL,
  `alamat_pt` varchar(200) DEFAULT NULL,
  `fakultas_pt` varchar(200) DEFAULT NULL,
  `jurusan_pt` varchar(200) DEFAULT NULL,
  `sks_pt` varchar(6) DEFAULT NULL,
  `telepon_mhs` varchar(20) DEFAULT NULL,
  `kode_pos` varchar(10) DEFAULT NULL,
  `sex` varchar(20) DEFAULT NULL,
  `kelas` varchar(50) DEFAULT NULL,
  `oleh` varchar(50) DEFAULT NULL,
  `tgl_update` varchar(50) DEFAULT NULL,
  `validasi` varchar(100) NOT NULL,
  `konsentrasi` int(5) DEFAULT '0',
  `tgl_masuk` varchar(100) DEFAULT '0',
  `kode_pt_awal` varchar(10) DEFAULT NULL,
  `nim_awal` varchar(20) DEFAULT NULL,
  `kode_jur_awal` varchar(20) DEFAULT NULL,
  `kode_jen_awal` varchar(10) DEFAULT NULL,
  `sks` int(10) DEFAULT '0',
  `lunas1` int(5) DEFAULT '0',
  `lunas2` int(5) DEFAULT '0',
  `lunas3` int(5) DEFAULT '0',
  `user_keuangan` varchar(50) DEFAULT NULL,
  `tgl_add` datetime DEFAULT NULL,
  `ip` varchar(30) DEFAULT NULL,
  `ipk` double DEFAULT '0',
  `stts` varchar(50) DEFAULT NULL,
  `orang_tua` varchar(50) DEFAULT NULL,
  `pekerjaan_ortu` varchar(30) DEFAULT NULL,
  `penghasilan_ayah` varchar(30) DEFAULT NULL,
  `nama_ibu` varchar(50) DEFAULT NULL,
  `pekerjaan_ibu` varchar(50) DEFAULT NULL,
  `penghasilan_ibu` varchar(30) DEFAULT NULL,
  `email` varchar(50) DEFAULT NULL,
  `alamat_desa` varchar(50) DEFAULT NULL,
  `alamat_kec` varchar(50) DEFAULT NULL,
  `alamat_kota` varchar(50) DEFAULT NULL,
  `alamat_prov` varchar(50) DEFAULT NULL,
  `nim_pt_mhs` varchar(20) DEFAULT NULL,
  `num_ubah` int(5) DEFAULT '0',
  `id_group` int(5) DEFAULT '0',
  `tahun_mk` int(10) DEFAULT NULL,
  `id_wali` int(10) DEFAULT NULL,
  `bebas_prog` int(10) DEFAULT NULL COMMENT '1 bebas',
  `stt_konversi` int(5) DEFAULT '0' COMMENT '0 = belum konversi 1 = sudah',
  `do` int(5) DEFAULT '0' COMMENT '0 = aktif 1=DO',
  `kartu_uts` int(5) DEFAULT '0',
  `kartu_uas` int(5) DEFAULT '0',
  `beban_sks` int(5) DEFAULT '0',
  `usr_dell` varchar(50) DEFAULT NULL,
  `smt_masuk` int(5) DEFAULT '1' COMMENT '1 = Ganjil 2 = Genap',
  `stt_lunas` int(10) DEFAULT '0',
  `tahun_masuk` int(10) DEFAULT NULL,
  `stt_dispen` int(10) DEFAULT '0' COMMENT '0 tutup 1 open',
  `beasiswa` int(10) DEFAULT '0',
  `ket_transfer` varchar(100) DEFAULT NULL,
  `jenis_pendaftaran` varchar(100) DEFAULT NULL,
  `jenis_beasiswa` varchar(100) DEFAULT NULL,
  `nisn` varchar(50) DEFAULT NULL,
  `tgl_masuk_mhs` date DEFAULT NULL,
  `stt_lulus` int(10) DEFAULT '0',
  `kode_fp` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`no_mhs`,`nim`),
  UNIQUE KEY `nim` (`nim`),
  KEY `no_mhs` (`no_mhs`)
) ENGINE=MyISAM AUTO_INCREMENT=34217 DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;

