CREATE TABLE `mata_kuliah2` (
  `id` int(255) NOT NULL AUTO_INCREMENT,
  `kode_fp` varchar(20) DEFAULT NULL,
  `urutan` int(20) DEFAULT '0',
  `kode_mk` varchar(20) NOT NULL,
  `kode_mk1` varchar(20) DEFAULT NULL,
  `kode_mk2` varchar(30) DEFAULT NULL,
  `nama_mk` varchar(250) NOT NULL,
  `sks` int(10) DEFAULT NULL,
  `kode_fakultas` varchar(5) NOT NULL,
  `kode_jurusan` varchar(5) NOT NULL,
  `semester` int(10) DEFAULT NULL,
  `tahun_akademik` varchar(20) DEFAULT NULL,
  `angkatan` varchar(5) NOT NULL,
  `syarat` varchar(200) DEFAULT NULL,
  `jenis` varchar(100) DEFAULT NULL,
  `kelompok` varchar(100) DEFAULT NULL,
  `konsen` varchar(250) DEFAULT 'Reguler',
  `konsentrasi` varchar(250) DEFAULT NULL,
  `tgl_update` date DEFAULT NULL,
  `oleh` varchar(100) DEFAULT NULL,
  `stt_tampil_smtr` varchar(40) DEFAULT NULL COMMENT '1 = tampil di ganjil dan genap 0 = tidak',
  `stt_bayar` varchar(10) NOT NULL DEFAULT '1',
  `stt_ta` int(10) NOT NULL DEFAULT '0',
  `kode_sinc` varchar(20) DEFAULT NULL,
  `thn_kurikulum` varchar(20) DEFAULT NULL,
  `stt_sinc` int(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`),
  KEY `kode_fp` (`kode_fp`)
) ENGINE=MyISAM AUTO_INCREMENT=18721 DEFAULT CHARSET=latin1;
