CREATE TABLE `program1` (
  `id_program` int(100) NOT NULL AUTO_INCREMENT,
  `tgl_add` datetime DEFAULT NULL,
  `tgl` varchar(2) DEFAULT NULL,
  `bln` varchar(2) DEFAULT NULL,
  `thn` varchar(4) DEFAULT NULL,
  `nim` varchar(20) DEFAULT NULL,
  `angkatan` int(20) DEFAULT NULL,
  `kode_fp` varchar(10) DEFAULT NULL,
  `kode_fakultas` varchar(3) DEFAULT NULL,
  `kode_jurusan` varchar(3) DEFAULT NULL,
  `semester` int(2) DEFAULT NULL,
  `kode_mk` varchar(10) DEFAULT NULL,
  `kode_mk1` varchar(10) DEFAULT NULL,
  `kode_mk2` varchar(10) DEFAULT NULL,
  `sks` int(1) DEFAULT '0',
  `program_ke` varchar(2) DEFAULT NULL,
  `status` varchar(1) DEFAULT NULL,
  `nilai` varchar(3) DEFAULT NULL,
  `keterangan` varchar(30) DEFAULT NULL,
  `kelas` varchar(20) DEFAULT NULL,
  `tahun_akademik` varchar(10) DEFAULT NULL,
  `operator` varchar(30) DEFAULT NULL,
  `ruang` varchar(10) DEFAULT NULL,
  `hapus` varchar(5) DEFAULT '0',
  `stt_ctk` int(5) NOT NULL DEFAULT '1',
  `tgl_program` varchar(20) DEFAULT NULL,
  `u_nilai` varchar(20) DEFAULT NULL,
  `tgl_nilai` varchar(20) DEFAULT NULL,
  `stt_bayar` varchar(10) DEFAULT '0',
  `u_program` varchar(200) DEFAULT NULL,
  `skor` int(5) DEFAULT '0',
  `kuis_dosen` int(5) DEFAULT '0' COMMENT '0 = belum, 1 = sudah',
  `id_kuliah_aktif` int(100) DEFAULT NULL,
  `tahun` varchar(30) DEFAULT NULL,
  `smtr` varchar(10) DEFAULT NULL,
  `konversi` int(10) DEFAULT '0' COMMENT '1 = Oke\r; \n2 = Split\r; 3 = Gabung',
  `n_aktf` int(10) DEFAULT '0',
  `n_quiz` int(10) DEFAULT '0',
  `n_tugas` int(10) DEFAULT '0',
  `n_uts` int(10) DEFAULT '0',
  `n_proyek` int(10) DEFAULT '0',
  `n_uas` int(10) DEFAULT '0',
  `stt_nilai` int(10) DEFAULT '1' COMMENT '1 = belum tampil, 2 = Tampil',
  `stt_wali` int(10) DEFAULT '0',
  `kelas_kuliah` varchar(100) DEFAULT '0',
  `nama_mk` varchar(100) DEFAULT NULL,
  `kuis_dosen2` varchar(5) DEFAULT '0' COMMENT '0 = belum, 1 = sudah',
  `a1` varchar(5) DEFAULT '0' COMMENT 'H I S',
  `a2` varchar(5) DEFAULT '0',
  `a3` varchar(5) DEFAULT '0',
  `a4` varchar(5) DEFAULT '0',
  `a5` varchar(5) DEFAULT '0',
  `a6` varchar(5) DEFAULT '0',
  `a7` varchar(5) DEFAULT '0',
  `a8` varchar(5) DEFAULT '0',
  `a9` varchar(5) DEFAULT '0',
  `a10` varchar(5) DEFAULT '0',
  `a11` varchar(5) DEFAULT '0',
  `a12` varchar(5) DEFAULT '0',
  `a13` varchar(5) DEFAULT '0' COMMENT 'H I S',
  `a14` varchar(5) DEFAULT '0',
  `a15` varchar(5) DEFAULT '0',
  `a16` varchar(5) DEFAULT '0',
  `kode_sinc` varchar(20) DEFAULT NULL,
  `smtr_masuk` int(10) NOT NULL DEFAULT '1' COMMENT '1 ganjil 2 genap',
  PRIMARY KEY (`id_program`),
  UNIQUE KEY `id_program` (`id_program`),
  KEY `nim` (`nim`)
) ENGINE=MyISAM AUTO_INCREMENT=1302606 DEFAULT CHARSET=latin1;