CREATE TABLE `setoran_data` (
  `id` int(100) NOT NULL AUTO_INCREMENT,
  `id_item` int(20) DEFAULT NULL,
  `kode_tran` varchar(20) DEFAULT NULL,
  `kode_item` varchar(20) DEFAULT NULL,
  `anggaran` varchar(10) DEFAULT NULL,
  `tgl_add` date DEFAULT NULL,
  `kode_fp` varchar(10) DEFAULT NULL,
  `kelompok` varchar(10) DEFAULT NULL,
  `tgl` int(10) DEFAULT NULL,
  `bln` int(10) DEFAULT NULL,
  `thn` int(10) DEFAULT NULL,
  `item` varchar(100) DEFAULT NULL,
  `jml` int(50) DEFAULT NULL,
  `jenis` varchar(30) DEFAULT NULL,
  `nim` varchar(20) DEFAULT NULL,
  `semester` int(10) DEFAULT NULL,
  `lunas` varchar(10) DEFAULT NULL,
  `kasir` varchar(30) DEFAULT NULL,
  `validasi` varchar(20) DEFAULT NULL,
  `stt_impor` int(5) DEFAULT '0',
  `keterangan` varchar(200) DEFAULT NULL,
  `jenis_tr` varchar(100) DEFAULT NULL,
  `jenis_mhs` varchar(100) DEFAULT NULL,
  `tgl_bank` varchar(20) DEFAULT NULL,
  `kode` varchar(10) DEFAULT NULL,
  `stt_mhs` int(10) DEFAULT '1' COMMENT '1 aktif 0 lulus',
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`),
  KEY `nim` (`nim`)
) ENGINE=MyISAM AUTO_INCREMENT=1037605 DEFAULT CHARSET=latin1;
