CREATE TABLE `setoran_mhs` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `angkatan` int(10) DEFAULT NULL,
  `kode_f` varchar(10) DEFAULT NULL,
  `kode_j` varchar(10) DEFAULT NULL,
  `prioritas` int(10) DEFAULT NULL,
  `kode_item` varchar(20) DEFAULT NULL,
  `item` varchar(200) DEFAULT NULL,
  `lunas` int(10) DEFAULT NULL,
  `gel` int(10) DEFAULT NULL,
  `sm1` int(100) DEFAULT NULL,
  `sm2` int(100) DEFAULT NULL,
  `sm3` int(100) DEFAULT NULL,
  `sm4` int(100) DEFAULT NULL,
  `sm5` int(100) DEFAULT NULL,
  `sm6` int(100) DEFAULT NULL,
  `sm7` int(100) DEFAULT NULL,
  `sm8` int(100) DEFAULT NULL,
  `sm9` int(100) DEFAULT NULL,
  `sm10` int(100) DEFAULT NULL,
  `sm11` int(100) DEFAULT NULL,
  `sm12` int(100) DEFAULT NULL,
  `sm13` int(100) DEFAULT NULL,
  `sm14` int(100) DEFAULT NULL,
  `stt` int(5) DEFAULT NULL,
  `sex` varchar(10) DEFAULT NULL,
  `kode_fp` varchar(10) DEFAULT NULL,
  `anggaran` varchar(10) DEFAULT NULL,
  `kelompok` varchar(5) DEFAULT NULL,
  `kode` varchar(10) DEFAULT NULL,
  `jenis` varchar(25) DEFAULT NULL,
  `smt_masuk` int(10) DEFAULT '1',
  `gel2` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=10576 DEFAULT CHARSET=latin1;
